name: 'london_cycling_analytics'
version: '1.0.0'
config-version: 2

profile: 'london_cycling_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  london_cycling_analytics:
    staging:
      materialized: view
    intermediate:
      materialized: table
    marts:
      materialized: table